
let freq = [
    {name: "Ready Hand", freq: 45.1},
    {name: "Value Tiles", freq: 40.0},
    {name: "All Simples", freq: 21.4},
    {name: "No-points hand", freq: 19.9},
    {name: "Self-pick", freq: 17.6},
    {name: "One-shot", freq: 10.2},
    {name: "Half-flush", freq: 6.31},
    {name: "One set of identical sequences", freq: 4.75},
    {name: "All triplet hand", freq: 3.92},
    {name: "Three colour straight", freq: 3.46},
    {name: "Seven pairs", freq: 2.52},
    {name: "Straight", freq: 1.75},
    {name: "Terminal or honor in each set", freq: 1.24},
    {name: "Flush", freq: 0.94},
    {name: "Three closed triplets", freq: 0.76},
    {name: "Last discard", freq: 0.63},
    {name: "Terminal in each set", freq: 0.38},
    {name: "Last tile", freq: 0.31},
    {name: "Dead wall draw", freq: 0.28},
    {name: "Double-ready", freq: 0.19},
    {name: "Little three dragons", freq: 0.15},
    {name: "All terminals and honors", freq: 0.08},
    {name: "Three colour triplets", freq: 0.05},
    {name: "Two sets of identical sequences", freq: 0.05},
    {name: "Robbing a quad", freq: 0.05},
    {name: "Four concealed triplets", freq: 0.049},
    {name: "Thirteen orphans", freq: 0.043},
    {name: "Big three dragons", freq: 0.039},
    {name: "four winds", freq: 0.012},
    {name: "All honors", freq: 0.008},
    {name: "Three kans", freq: 0.005},
    {name: "All terminals", freq: 0.00181},
    {name: "Hand of earth", freq: 0.00158},
    {name: "All green", freq: 0.0011},
    {name: "Nine gates", freq: 0.00045},
    {name: "Heavenly hand", freq: 0.0003025},
    {name: "Four kans", freq: 0.0002},
]

export default freq